# Generated by Django 5.2.1 on 2025-05-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the service was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the service was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user_type', models.CharField(choices=[('Rider', 'Rider'), ('Driver', 'Driver')], max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
