# Generated by Django 5.2.1 on 2025-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='current_location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
