from utils.constants import (
    RIDER,
    DRIVER,
    REQUESTED,
    ACCEPTED,
    STARTED,
    COMPLETED,
    CANCELLED
)


USER_TYPES = (
    (RIDER, RIDER),
    (DRIVER, DRIVER),
)

RIDE_STATUS = (
    (REQUESTED, REQUESTED),
    (ACCEPTED, ACCEPTED),
    (STARTED, STARTED),
    (COMPLETED, COMPLETED),
    (CANCELLED, CANCELLED),
)